name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macOS-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.app
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=macOS,variant=Mac Catalyst"
          - "platform=iOS Simulator,name=iPhone 15"
          - "platform=tvOS Simulator,name=Apple TV"
          - "platform=visionOS Simulator,name=Apple Vision Pro"
          - "platform=watchOS Simulator,name=Apple Watch Series 9 (41mm)"

    steps:
      - uses: actions/checkout@v4
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme Lock -destination "${{ matrix.destination }}" test | xcbeautify
